/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-21 08:48:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.mainpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TripFul_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Tripful - 관광지 정보</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .hero-image {\r\n");
      out.write("            background-image: url('../image/IMG_0104.JPEG');\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            border-radius: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("        main {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm px-4\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("        <img src=\"../image/tripful.png\" alt=\"Tripful Logo\" height=\"50\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarNavDropdown\">\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\">지역별 관광지</a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">서울</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">부산</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">제주</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"d-flex align-items-center\">\r\n");
      out.write("            <span id=\"welcome-text\" class=\"me-3 text-secondary\">로그인을 해주세요</span>\r\n");
      out.write("            <button id=\"auth-button\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<main class=\"container my-4\">\r\n");
      out.write("    <div class=\"hero-image d-flex justify-content-center align-items-center text-white shadow mb-5\">\r\n");
      out.write("        <h1 class=\"display-4 bg-dark bg-opacity-50 p-4 rounded\">대한민국 관광 명소를 한눈에!</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 검색 바 -->\r\n");
      out.write("    <div class=\"mb-4\">\r\n");
      out.write("        <form class=\"d-flex\">\r\n");
      out.write("            <input class=\"form-control me-2\" type=\"search\" placeholder=\"관광지를 검색해보세요...\" aria-label=\"Search\">\r\n");
      out.write("            <button class=\"btn btn-outline-success\" type=\"submit\">검색</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 지역별 관광지 카드 -->\r\n");
      out.write("    <h2 class=\"mb-3\">추천 관광지</h2>\r\n");
      out.write("    <div class=\"row row-cols-1 row-cols-md-3 g-4 mb-5\">\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"../image/seoul.jpg\" class=\"card-img-top\" alt=\"서울\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">서울</h5>\r\n");
      out.write("                    <p class=\"card-text\">역사와 현대가 어우러진 대한민국 수도 서울.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">자세히 보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"../image/busan.jpg\" class=\"card-img-top\" alt=\"부산\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">부산</h5>\r\n");
      out.write("                    <p class=\"card-text\">바다와 도심이 공존하는 아름다운 항구 도시.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">자세히 보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"card h-100 shadow-sm\">\r\n");
      out.write("                <img src=\"../image/jeju.jpg\" class=\"card-img-top\" alt=\"제주\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <h5 class=\"card-title\">제주</h5>\r\n");
      out.write("                    <p class=\"card-text\">자연의 경이로움이 살아 숨 쉬는 섬 제주도.</p>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-primary\">자세히 보기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 리뷰/추천 섹션 -->\r\n");
      out.write("    <h2 class=\"mb-3\">여행자들의 리뷰</h2>\r\n");
      out.write("    <div class=\"list-group mb-5\">\r\n");
      out.write("        <div class=\"list-group-item\">\r\n");
      out.write("            <h5 class=\"mb-1\">서울 경복궁이 정말 멋졌어요!</h5>\r\n");
      out.write("            <p class=\"mb-1\">역사와 전통을 직접 느낄 수 있어요. 한복 체험도 추천합니다.</p>\r\n");
      out.write("            <small>by 여행자A</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"list-group-item\">\r\n");
      out.write("            <h5 class=\"mb-1\">부산 해운대는 낮과 밤 모두 최고!</h5>\r\n");
      out.write("            <p class=\"mb-1\">야경이 특히 아름다워요. 광안대교도 꼭 보세요.</p>\r\n");
      out.write("            <small>by 여행자B</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"list-group-item\">\r\n");
      out.write("            <h5 class=\"mb-1\">제주도 오름 등반, 강추!</h5>\r\n");
      out.write("            <p class=\"mb-1\">바람과 경치가 정말 좋아요. 조용히 힐링하기에 제격이에요.</p>\r\n");
      out.write("            <small>by 여행자C</small>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-dark text-white text-center py-4 mt-auto\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <p class=\"mb-1\">Address: 1234 Street, City, Country</p>\r\n");
      out.write("        <p class=\"mb-0\">Tel: +123 456 7890</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const authButton = document.getElementById('auth-button');\r\n");
      out.write("    const welcomeText = document.getElementById('welcome-text');\r\n");
      out.write("    let loggedIn = false;\r\n");
      out.write("\r\n");
      out.write("    authButton.addEventListener('click', () => {\r\n");
      out.write("        loggedIn = !loggedIn;\r\n");
      out.write("        if (loggedIn) {\r\n");
      out.write("            welcomeText.textContent = 'taelim34 님 환영합니다';\r\n");
      out.write("            authButton.textContent = 'Logout';\r\n");
      out.write("            authButton.classList.remove('btn-primary');\r\n");
      out.write("            authButton.classList.add('btn-danger');\r\n");
      out.write("        } else {\r\n");
      out.write("            welcomeText.textContent = '로그인을 해주세요';\r\n");
      out.write("            authButton.textContent = 'Login';\r\n");
      out.write("            authButton.classList.remove('btn-danger');\r\n");
      out.write("            authButton.classList.add('btn-primary');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
